config/routes.rb
Cab::Application.routes.draw do
  match '/contact',     :to => 'pages#contact'
  match '/about',       :to => 'pages#about'
  match '/services',    :to => 'pages#services'
  root                  :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

  def services
    @title = "Services"
  end

  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis
  def title
    base_title = "Cab Quality Construction"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
This is the footer
</footer>

app/views/layouts/_header.html.erb
<header class="group box-shadow">
  <div id="logo" class="group"> 
  <!-- TD move this to helper -->
  <% logo = image_tag("cablogo.png", :alt => "Cab Quality Construction") %>
     <h1>
        <%= link_to logo, root_path %>  
     </hi>

  </div>

  <div id="nav">
    <ul class="group">
        <li>
          <%= link_to root_path do %>
            <strong>Home <em> Our Work</em></strong>
          <% end %>
        </li>
        <li>
          <%= link_to about_path do %>
            <strong>About Us <em> History</em></strong>
          <% end %>
        </li>
        <li>
          <%= link_to services_path do %>
            <strong>Services <em> What we do</em></strong>
          <% end %>
        </li>
        <li>
          <%= link_to contact_path do %>
            <strong>Free Estimates <em> Contact Us</em></strong>
          <% end %>
        </li>
    </ul>
  </div>
  <div id="header_bottom_logo">
    <h1>&nbsp;</h1>
  </div>
</header>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="cabQualityConstruction">
<%= render 'layouts/header' %>
<div id="wrap" class="box-shadow">
  <div class="main">
  <%= yield %>
  </div><!-- ending main div -->
</div><!-- ending wrap div -->
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>
<p>CAB Quality Construction is a full service general contractor located in Marshall, MInnesota. Founded in year, we have been committed to producing quality homes in this area since that time. We employ approximately how many people.</p>

app/views/pages/contact.html.erb
<h2>Contact Us</h2>
<p>If you are thinking about a new home or residential remodeling, please contact CAB Quality Construction. You can be assured that you will be treated in a professional and courteous manner as we work together to plan, manage and complete your construction project.</p>

app/views/pages/home.html.erb
<h2>Our Work</h2>
	
<div class="entry group">
	<h3>New Home Construction</h3>
		
	<ul class="entry-meta">
		<li><h4>Oct 26, 2010</h4></li>
		<li>Posted at 09:37 <abbr>PM</abbr></li>
	</ul>
</div>
<div id="picture_container">
	<ul class="slides">
		<li><img src="#" alt="Outside House 1" /></li>
		<li><img src="#" alt="Outside House 1" /></li>
		<li><img src="#" alt="Outside House 1" /></li>
		<li><img src="#" alt="Outside House 1" /></li>
		<li><img src="#" alt="Outside House 1" /></li>
	</ul>
</div>	 	

app/views/pages/services.html.erb
<h2>Services</h2>
<p>At Cab construction we specialize in new home construction. Our commitment to quality ensures that your new home will be built on budget and on time.  We also do remodels, expansions and roof repair.</p>